#!/usr/bin/env zsh

set -u

usage() {
    cat 1>&2 <<EOF
brewp
A useful tool for managing homebrew packages.

USAGE:
    brewp <command|package> [OPTIONS]

COMMANDS:
    install                 Install uninstalled packages
    clean                   Remove files created by brewp

OPTIONS:
    -h, --help              Print help information
    --cask                  Mark as cask packages
    --tap                   Mark as taps
EOF
}

say() {
    echo "brewp: $@"
}

err() {
    say "$@" >&2
    exit 1
}

check_cmd() {
    command -v "$1" >/dev/null 2>&1
    return $?
}

need_cmd() {
    if ! check_cmd "$1"; then
        err "need '$1' (command not found)"
    fi
}

parse_args() {
    # No arguments
    if [[ $# -eq 0 ]]; then
        usage
        exit 1
    fi

    # check if we have to use /dev/tty to prompt the user
    local need_tty=yes
    for arg in "$@"; do
        case "$arg" in
            -h|--help)
                usage
                exit 0
                ;;
            -y)
                # user wants to skip the prompt -- we don't need /dev/tty
                need_tty=no
                ;;
            *)
                ;;
        esac
    done
}

CACHE_DIR=${XDG_CACHE_HOME:-$HOME/.cache}/brewp
DATA_DIR=${XDG_DATA_HOME:-$HOME/.local/share}/brewp

TAP_LIST="$CACHE_DIR/taps.txt"
PACKAGE_LIST="$CACHE_DIR/packages.txt"
CASK_PACKAGE_LIST="$CACHE_DIR/cask_packages.txt"

INSTALLED_TAP_LIST="$DATA_DIR/brew-taps.txt"
INSTALLED_PACKAGE_LIST="$DATA_DIR/brew-packages.txt"
INSTALLED_CASK_PACKAGE_LIST="$DATA_DIR/brew-cask-packages.txt"

clean() {
    rm -rf "$CACHE_DIR"
    rm -rf "$DATA_DIR"
}

install_impl() {
    local list_path="$1"
    local installed_list_path="$2"
    local list_command="$3"
    local install_command="$4"

    local installed_list
    if test $(find "$installed_list_path" -mtime -1 2>/dev/null); then
        installed_list="$(cat $installed_list_path)"
    else
        installed_list="$(eval brew $list_command)"
        echo "$installed_list" >! "$installed_list_path"
    fi

    local is_anything_installed=false
    for line in "${(@f)"$(<$list_path)"}"
    do
        if [[ ! $installed_list =~ $line ]]; then
            is_anything_installed=true
            eval "brew $install_command $line"
        fi
    done

    # Update the installed list if anything was installed
    if "${is_anything_installed}"; then
        installed_list="$(eval brew $list_command)"
        echo "$installed_list" >! "$installed_list_path"
    fi
}

install() {
    if [[ ! -d $DATA_DIR ]]; then
        mkdir $DATA_DIR # TODO: when error, another brewp process is working
    fi

    if [[ -f "$TAP_LIST" ]]; then
        install_impl "$TAP_LIST" "$INSTALLED_TAP_LIST" "tap" "tap"
    fi
    if [[ -f "$PACKAGE_LIST" ]]; then
        install_impl "$PACKAGE_LIST" "$INSTALLED_PACKAGE_LIST" "list --formula -1" "install"
    fi
    # Cask is only for macOS
    if [[ -f "$CASK_PACKAGE_LIST" ]] && [[ "$OSTYPE" == darwin* ]]; then
        install_impl "$CASK_PACKAGE_LIST" "$INSTALLED_CASK_PACKAGE_LIST" "list --cask -1" "install --cask"
    fi

    rm -rf "$CACHE_DIR"
}

push() {
    local pacakage_name="$1"
    local package_list_path="$PACKAGE_LIST"

    if [[ ! -d $CACHE_DIR ]]; then
        mkdir $CACHE_DIR # TODO: when error, another brewp process is working
    fi

    if [[ $# -eq 2 ]]; then
        if [[ "$2" = '--cask' ]]; then
            # Cask is only for macOS
            if [[ "$OSTYPE" != darwin* ]]; then
                return
            fi
            package_list_path="$CASK_PACKAGE_LIST"
        elif [[ "$2" = '--tap' ]]; then
            package_list_path="$TAP_LIST"
        fi
    fi

    echo $pacakage_name >>! $package_list_path
}

main() {
    need_cmd brew
    need_cmd echo
    need_cmd mkdir
    need_cmd rm
    need_cmd cat
    need_cmd find

    parse_args $@

    case "${@[1]}" in
        install)
            install
            ;;
        clean)
            clean
            ;;
        *)
            push $@
            ;;
    esac
}

main "$@" || exit 1
