name: Rust

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy --all-targets --all-features -- -D clippy::all -D warnings
